### ISSUE TITLE
GUI mit dem Buchungssystem verbinden.

### ISSUE THREAD

**Issue by Murat-Dursun** [MarcelKoschinsky/SoftwareEngineeringBuchungssystem#17]
Die Daten über die GUI aufnehmen und an die Methode bucheRaum weitergeben. Die Ausgabe sollte auch auf der GUI erfolgen.

**Comment by Murat-Dursun** [comment]
GUI ist verbunden, es muss nurnoch bucheRaum in String konvertiert werden. Ist es String, müssen die Zeilen 81, 91 und 101 wieder eingebaut werden und die Zeile 127 wird ein und 128 auskommentiert.

**Comment by JanikLuett** [comment]
RaumManager ist angepasst und gibt jetzt Strings zurück.

Die betreffenden Stellen in der GUI habe ich angepasst bzw. die Parse-Operationen mussten weiter nach unten (in "actionPerformed") verschoben werden, wegen NullPointerExceptions.

Es können jetzt Räume gebucht werden und doppelte Buchungen werden mit Fehlermeldung abgelehnt.
